---
name: maybe
version: 0.0202
author:
  - 'Piotr Roszatycki <dexter@cpan.org>'
abstract: Use a Perl module and ignore error if can't be loaded
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=maybe
  license: http://dev.perl.org/licenses/
  repository: http://dexter-cpan.googlecode.com/svn/maybe
requires:
  perl: 5.006
provides:
  maybe:
    file: lib/maybe.pm
    version: 0.0202
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
