---
name: maybe
version: 0.01
author:
  - 'Piotr Roszatycki <dexter@debian.org>'
abstract: use a Perl module and ignore error if can't be loaded
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  perl: 5.006
provides:
  maybe:
    file: lib/maybe.pm
    version: 0.01
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
